# Generated by Django 4.0.5 on 2022-08-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0080_circle_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='circle_creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
