# Generated by Django 4.0.5 on 2022-08-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0081_alter_circle_circle_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='circle_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='circle_creator', to='basic.userregister'),
        ),
    ]
